<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../AlchiwebApp.Build.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <CoreCompileDependsOn>PrepareResources;$(CompileDependsOn)</CoreCompileDependsOn>
        <IsAotCompatible>true</IsAotCompatible>
		<PublishAot>true</PublishAot>
	</PropertyGroup>

</Project>
