<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../AlchiwebApp.Build.props" />

    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <AssemblyName>Ardalis.Specification.EntityFrameworkCore</AssemblyName>
        <PackageId>AlchiwebApp.Ardalis.Specification.EntityFrameworkCore</PackageId>
        <Title>AlchiwebApp.Ardalis.Specification.EntityFrameworkCore</Title>
        <Description>AlchiwebApp version of EF Core plugin package to Ardalis.Specification containing EF Core evaluator and abstract repository.</Description>
        <Summary>AlchiwebApp version of EF Core plugin package to Ardalis.Specification containing EF Core evaluator and abstract repository.</Summary>
    
        <PackageTags>spec;specification;repository;ddd;ef;ef core;entity framework;entity framework core;alchiweb</PackageTags>
        <PackageReleaseNotes>
            Based on Ardalis.Specification.EntityFrameworkCore v9.3.1.
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.GuardClauses" />
        <PackageReference Include="Ardalis.Specification" />
        <PackageReference Include="Mediator.Abstractions" />

        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AlchiwebApp.PagingFiltering\AlchiwebApp.PagingFiltering.csproj" />
    </ItemGroup>
</Project>
